apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-service-deployment
  labels:
    app: manager-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-service
  template:
    metadata:
      labels:
        app: manager-service
    spec:
      containers:
        - name: manager-service
          image: simenravnik/manager-service:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: manager-service-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: manager-service
